name: Docker build and push to GAR

permissions:
  contents: read
  id-token: write
  attestations: write

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
    paths:
      - '!infra/go-demo-app/**'
      - '!README.md'
      - 'infra/Dockerfile'
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches: [ 'main' ]
    paths:
      - '!infra/go-demo-app/**'
      - '!README.md'
      - 'infra/Dockerfile'
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  workflow_dispatch:

jobs:
  generate-build-id:
    runs-on: ubuntu-latest
    outputs:
      BUILD_ID: ${{ steps.prep.outputs.BUILD_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "BUILD_ID=${branch}-${sha}-${ts}" >> $GITHUB_OUTPUT

  build-and-push-docker-image-to-gar:
    needs: generate-build-id
    uses: andreistefanciprian/gh-reusable-workflows/.github/workflows/build_and_push_docker_image_to_gar.yaml@main
    with:
      app_name: go-demo-app
      build_id: ${{ needs.generate-build-id.outputs.BUILD_ID }}
      context: .
      dockerfile: ./infra/Dockerfile
    secrets: inherit