name: helm

permissions:
  contents: read
  id-token: write

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
    paths:
      - 'infra/go-demo-app/**'
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'infra/go-demo-app/**'
      - '.github/workflows/helm.yaml'
  workflow_dispatch:

# env:
#   CHART_VERSION: "${{ github.sha::8 }}-${{ github.run_number }}"
#   # CHART_VERSION: "$(git describe --tags --abbrev=0)-${{ github.run_number }}"
  
jobs:
  helm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the latest Git tag
        id: get-latest-tag
        run: |
          echo "latest_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: '${{ secrets.WI_POOL_PROVIDER_ID }}'
          service_account: '${{ secrets.PACKAGER_GSA_ID }}'
          token_format: 'access_token'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: latest

      - name: Login to GCP Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY_HOST_NAME }} --quiet
          
      - name: Helm package
        run: |
          helm package infra/go-demo-app --version $CHART_VERSION
        env:
          CHART_VERSION: ${{ steps.get-latest-tag.outputs.latest_tag }}-${{ github.run_number }}

      - name: Helm push
        run: |
          helm push go-demo-app-$CHART_VERSION.tgz oci://${{ secrets.ARTIFACT_REGISTRY_HOST_NAME }}/${{ secrets.PROJECT_ID }}/${{ secrets.HELM_REPO_ID }} --debug
        env:
          CHART_VERSION: ${{ steps.get-latest-tag.outputs.latest_tag }}-${{ github.run_number }}