name: test_build_and_push

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
    paths:
      - '!infra/go-demo-app/**'
      - '!README.md'
  pull_request:
    branches: [ 'main' ]
    paths:
      - '!infra/go-demo-app/**'
      - '!README.md'
      - '.github/workflows/test_and_push_image.yaml'
      
  workflow_dispatch:

jobs:

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  build-and-push-gcr:
    needs: unit-test
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1
        name: Authenticate to Google Cloud
        with:
          workload_identity_provider: '${{ secrets.WI_POOL_PROVIDER_ID }}'
          service_account: '${{ secrets.PACKAGER_GSA_ID }}'
          token_format: 'access_token'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: latest

      - name: Login to GCP Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY_HOST_NAME }} --quiet

      - name: Build Docker image
        run: docker build -f infra/Dockerfile . -t ${{ secrets.ARTIFACT_REGISTRY_HOST_NAME }}/${{ secrets.PROJECT_ID }}/${{ secrets.IMAGE_REPO_ID }}/dev/${{ github.repository }}:${{ github.sha }}-${{ github.run_number }}

      - name: Push Docker image
        run: docker push ${{ secrets.ARTIFACT_REGISTRY_HOST_NAME }}/${{ secrets.PROJECT_ID }}/${{ secrets.IMAGE_REPO_ID }}/dev/${{ github.repository }}:${{ github.sha }}-${{ github.run_number }}