name: build_and_test

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
    paths:
      - '!infra/go-demo-app/**'
      - '!README.md'
  pull_request:
    branches: [ 'main' ]
    paths:
      - '!infra/go-demo-app/**'
      - '!README.md'
      
  workflow_dispatch:

jobs:
  # docker-build-push:
  #   needs: unit-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     -
  #       name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v3
  #       with:
  #         file: infra/Dockerfile
  #         push: true
  #         tags: ${{ github.repository }}:${{ github.sha }}


  build-and-push-gcr:
    needs: unit-test
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v1
        name: Authenticate to Google Cloud
        with:
          workload_identity_provider: '${{ secrets.WI_POOL_PROVIDER_ID }}'
          service_account: '${{ secrets.PACKAGER_GSA_ID }}'
          token_format: 'access_token'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: latest

      # - name: Login to GCP Container Registry
      #   run: |
      #     gcloud auth configure-docker ${{ secrets.CONTAINER_REGISTRY_HOST_NAME }} --quiet

      # - name: Build Docker image
      #   run: docker build -f infra/Dockerfile . -t ${{ secrets.CONTAINER_REGISTRY_HOST_NAME }}/${{ secrets.PROJECT_ID }}/${{ github.repository }}:${{ github.sha }}

      # - name: Push Docker image
      #   run: docker push ${{ secrets.CONTAINER_REGISTRY_HOST_NAME }}/${{ secrets.PROJECT_ID }}/${{ github.repository }}:${{ github.sha }}

      - name: Login to GCP Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.ARTIFACT_REGISTRY_HOST_NAME }} --quiet

      - name: Build Docker image
        run: docker build -f infra/Dockerfile . -t ${{ secrets.ARTIFACT_REGISTRY_HOST_NAME }}/${{ secrets.PROJECT_ID }}/container-images/dev/go-demo-app:${{ github.sha }}

      - name: Push Docker image
        run: docker push ${{ secrets.ARTIFACT_REGISTRY_HOST_NAME }}/${{ secrets.PROJECT_ID }}/container-images/dev/go-demo-app:${{ github.sha }}

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...