name: build_and_test

on:
  push:
    branches:
      - 'main'
    paths:
      - '!infra/go-demo-app/**'
      - '!README.md'
  pull_request:
    branches: [ 'main' ]
    paths:
      - '!infra/go-demo-app/**'
      - '!README.md'
  workflow_dispatch:

jobs:
  docker-build-push:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: infra/Dockerfile
          push: true
          tags: ${{ github.repository }}:${{ github.sha }}

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...